### ISSUE TITLE
Got following error while installing it on my vps

### ISSUE THREAD

**Issue by HackerAndya** [r3curs1v3-pr0xy/vajra#1]
> event@1.0.0 postinstall /home/ubuntu/vajra/node_modules/event
> npm dedup

npm ERR! code EACCES
npm ERR! syscall scandir
npm ERR! path /root/.npm/_logs
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1000:1000 "/root/.npm"
glob error [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/root/.npm/_logs'
}
npm ERR! correctMkdir failed to make directory /root/.npm/_locks
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /root/.npm/_locks
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1000:1000 "/root/.npm"
npm WARN almightron@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 243
npm ERR! event@1.0.0 postinstall: `npm dedup`
npm ERR! Exit status 243
npm ERR!
npm ERR! Failed at the event@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-13T07_44_00_713Z-debug.log

> event@1.0.0 postinstall /home/ubuntu/vajra/node_modules/event
> npm dedup

npm ERR! code EACCES
npm ERR! syscall scandir
npm ERR! path /root/.npm/_logs
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1000:1000 "/root/.npm"
glob error [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/root/.npm/_logs'
}
npm ERR! correctMkdir failed to make directory /root/.npm/_locks
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /root/.npm/_locks
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1000:1000 "/root/.npm"
npm WARN almightron@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 243
npm ERR! event@1.0.0 postinstall: `npm dedup`
npm ERR! Exit status 243
npm ERR!
npm ERR! Failed at the event@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-13T07_44_04_580Z-debug.log

> event@1.0.0 postinstall /home/ubuntu/vajra/node_modules/event
> npm dedup

npm ERR! code EACCES
npm ERR! syscall scandir
npm ERR! path /root/.npm/_logs
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1000:1000 "/root/.npm"
glob error [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/root/.npm/_logs'
}
npm ERR! correctMkdir failed to make directory /root/.npm/_locks
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /root/.npm/_locks
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1000:1000 "/root/.npm"
npm WARN almightron@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 243
npm ERR! event@1.0.0 postinstall: `npm dedup`
npm ERR! Exit status 243
npm ERR!
npm ERR! Failed at the event@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-13T07_44_08_196Z-debug.log

> event@1.0.0 postinstall /home/ubuntu/vajra/node_modules/event
> npm dedup

npm ERR! code EACCES
npm ERR! syscall scandir
npm ERR! path /root/.npm/_logs
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1000:1000 "/root/.npm"
glob error [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/root/.npm/_logs'
}
npm ERR! correctMkdir failed to make directory /root/.npm/_locks
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /root/.npm/_locks
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1000:1000 "/root/.npm"
npm WARN notsup Unsupported engine for follow@0.11.4: wanted: {"node":"0.10.x || 0.8.x"} (current: {"node":"14.16.0","npm":"6.14.11"})
npm WARN notsup Not compatible with your version of node/npm: follow@0.11.4
npm WARN almightron@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 243
npm ERR! event@1.0.0 postinstall: `npm dedup`
npm ERR! Exit status 243
npm ERR!
npm ERR! Failed at the event@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-13T07_44_11_986Z-debug.log

> event@1.0.0 postinstall /home/ubuntu/vajra/node_modules/event
> npm dedup

npm ERR! code EACCES
npm ERR! syscall scandir
npm ERR! path /root/.npm/_logs
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1000:1000 "/root/.npm"
glob error [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/root/.npm/_logs'
}
npm ERR! correctMkdir failed to make directory /root/.npm/_locks
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /root/.npm/_locks
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1000:1000 "/root/.npm"
npm WARN almightron@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 243
npm ERR! event@1.0.0 postinstall: `npm dedup`
npm ERR! Exit status 243
npm ERR!
npm ERR! Failed at the event@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-13T07_44_16_017Z-debug.log

> event@1.0.0 postinstall /home/ubuntu/vajra/node_modules/event
> npm dedup

npm ERR! code EACCES
npm ERR! syscall scandir
npm ERR! path /root/.npm/_logs
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1000:1000 "/root/.npm"
glob error [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/root/.npm/_logs'
}
npm ERR! correctMkdir failed to make directory /root/.npm/_locks
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /root/.npm/_locks
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1000:1000 "/root/.npm"
npm WARN almightron@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 243
npm ERR! event@1.0.0 postinstall: `npm dedup`
npm ERR! Exit status 243
npm ERR!
npm ERR! Failed at the event@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-13T07_44_20_074Z-debug.log

> event@1.0.0 postinstall /home/ubuntu/vajra/node_modules/event
> npm dedup

npm ERR! code EACCES
npm ERR! syscall scandir
npm ERR! path /root/.npm/_logs
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1000:1000 "/root/.npm"
glob error [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/root/.npm/_logs'
}
npm ERR! correctMkdir failed to make directory /root/.npm/_locks
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /root/.npm/_locks
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1000:1000 "/root/.npm"
npm WARN almightron@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 243
npm ERR! event@1.0.0 postinstall: `npm dedup`
npm ERR! Exit status 243
npm ERR!
npm ERR! Failed at the event@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-13T07_44_23_613Z-debug.log

> event@1.0.0 postinstall /home/ubuntu/vajra/node_modules/event
> npm dedup

npm ERR! code EACCES
npm ERR! syscall scandir
npm ERR! path /root/.npm/_logs
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1000:1000 "/root/.npm"
glob error [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/root/.npm/_logs'
}
npm ERR! correctMkdir failed to make directory /root/.npm/_locks
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /root/.npm/_locks
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1000:1000 "/root/.npm"
npm WARN almightron@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 243
npm ERR! event@1.0.0 postinstall: `npm dedup`
npm ERR! Exit status 243
npm ERR!
npm ERR! Failed at the event@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-13T07_44_27_175Z-debug.log

> event@1.0.0 postinstall /home/ubuntu/vajra/node_modules/event
> npm dedup

npm ERR! code EACCES
npm ERR! syscall scandir
npm ERR! path /root/.npm/_logs
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1000:1000 "/root/.npm"
glob error [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/root/.npm/_logs'
}
npm ERR! correctMkdir failed to make directory /root/.npm/_locks
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /root/.npm/_locks
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1000:1000 "/root/.npm"
npm WARN almightron@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 243
npm ERR! event@1.0.0 postinstall: `npm dedup`
npm ERR! Exit status 243
npm ERR!
npm ERR! Failed at the event@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-13T07_44_30_698Z-debug.log
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142

> event@1.0.0 postinstall /home/ubuntu/vajra/node_modules/event
> npm dedup

npm ERR! code EACCES
npm ERR! syscall scandir
npm ERR! path /root/.npm/_logs
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1000:1000 "/root/.npm"
glob error [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/root/.npm/_logs'
}
npm ERR! correctMkdir failed to make directory /root/.npm/_locks
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /root/.npm/_locks
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1000:1000 "/root/.npm"
npm WARN almightron@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 243
npm ERR! event@1.0.0 postinstall: `npm dedup`
npm ERR! Exit status 243
npm ERR!
npm ERR! Failed at the event@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-13T07_44_36_086Z-debug.log

> event@1.0.0 postinstall /home/ubuntu/vajra/node_modules/event
> npm dedup

npm ERR! code EACCES
npm ERR! syscall scandir
npm ERR! path /root/.npm/_logs
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1000:1000 "/root/.npm"
glob error [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/root/.npm/_logs'
}
npm ERR! correctMkdir failed to make directory /root/.npm/_locks
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /root/.npm/_locks
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1000:1000 "/root/.npm"
npm WARN almightron@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 243
npm ERR! event@1.0.0 postinstall: `npm dedup`
npm ERR! Exit status 243
npm ERR!
npm ERR! Failed at the event@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-13T07_44_40_747Z-debug.log

> event@1.0.0 postinstall /home/ubuntu/vajra/node_modules/event
> npm dedup

npm ERR! code EACCES
npm ERR! syscall scandir
npm ERR! path /root/.npm/_logs
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1000:1000 "/root/.npm"
glob error [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/root/.npm/_logs'
}
npm ERR! correctMkdir failed to make directory /root/.npm/_locks
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /root/.npm/_locks
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1000:1000 "/root/.npm"
npm WARN almightron@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 243
npm ERR! event@1.0.0 postinstall: `npm dedup`
npm ERR! Exit status 243
npm ERR!
npm ERR! Failed at the event@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-13T07_44_44_327Z-debug.log

> event@1.0.0 postinstall /home/ubuntu/vajra/node_modules/event
> npm dedup

npm ERR! code EACCES
npm ERR! syscall scandir
npm ERR! path /root/.npm/_logs
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1000:1000 "/root/.npm"
glob error [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/root/.npm/_logs'
}
npm ERR! correctMkdir failed to make directory /root/.npm/_locks
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /root/.npm/_locks
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1000:1000 "/root/.npm"
npm WARN almightron@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 243
npm ERR! event@1.0.0 postinstall: `npm dedup`
npm ERR! Exit status 243
npm ERR!
npm ERR! Failed at the event@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-13T07_44_47_859Z-debug.log

> event@1.0.0 postinstall /home/ubuntu/vajra/node_modules/event
> npm dedup

npm ERR! code EACCES
npm ERR! syscall scandir
npm ERR! path /root/.npm/_logs
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1000:1000 "/root/.npm"
glob error [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/root/.npm/_logs'
}
npm ERR! correctMkdir failed to make directory /root/.npm/_locks
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /root/.npm/_locks
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1000:1000 "/root/.npm"
npm WARN almightron@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 243
npm ERR! event@1.0.0 postinstall: `npm dedup`
npm ERR! Exit status 243
npm ERR!
npm ERR! Failed at the event@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-13T07_44_51_569Z-debug.log

> event@1.0.0 postinstall /home/ubuntu/vajra/node_modules/event
> npm dedup

npm ERR! code EACCES
npm ERR! syscall scandir
npm ERR! path /root/.npm/_logs
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1000:1000 "/root/.npm"
glob error [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/root/.npm/_logs'
}
npm ERR! correctMkdir failed to make directory /root/.npm/_locks
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /root/.npm/_locks
npm ERR! errno -13
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1000:1000 "/root/.npm"
npm WARN almightron@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 243
npm ERR! event@1.0.0 postinstall: `npm dedup`
npm ERR! Exit status 243
npm ERR!
npm ERR! Failed at the event@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-13T07_44_55_363Z-debug.log

**Comment by r3curs1v3-pr0xy** [comment]
You can ignore this. It has no effect on the framework.
