### ISSUE TITLE
General question

### ISSUE THREAD

**Issue by bootyhunt3r** [r3curs1v3-pr0xy/vajra#10]
Hello @r3curs1v3-pr0xy  , So I initiated a task for a domain and when I went to that result , it's showing a black page (see in the screenshot)
![Screenshot (18)](https://user-images.githubusercontent.com/68128478/111068436-b9401680-84ee-11eb-9117-e5cf1960f0c7.png)

Does this mean that it doesn't have any CVE running or there's an error going on ?

**Comment by bootyhunt3r** [comment]
I also did some more scans but they are not showing up on the results.
![Screenshot (19)](https://user-images.githubusercontent.com/68128478/111068646-a11cc700-84ef-11eb-8940-5a1802fd21ba.png)

**Comment by r3curs1v3-pr0xy** [comment]
It means your target is not vulnerable for any CVE's. For more information on how Vajra works, You can read this post: https://hackwithproxy.medium.com/introducing-vajra-an-advanced-web-hacking-framework-bd8307a01aa8.

One more thing, change your default username and password now as anyone can log in to your panel.

**Comment by bootyhunt3r** [comment]
Thanks for the info and what's the reason for the other thing ? Results not showing up in the result section ?

**Comment by r3curs1v3-pr0xy** [comment]
Which Scan you performed? Like if you run subdomain takeover then the result will be shown only if it is vulnerable to subdomain takeover.

**Comment by bootyhunt3r** [comment]
I did javascript can

**Comment by r3curs1v3-pr0xy** [comment]
Okay, Javascript is fetched and filtered from gau tool. If target data is not available in archive.org or if its available but the found javascript doesn't gives 200 response code then it will not show up in result. I clearly mentioned that in the medium post.

**Comment by bootyhunt3r** [comment]
I also did extract endpoints scan but it's also not showing up in the results.

**Comment by r3curs1v3-pr0xy** [comment]
There could be two reason for this. Either your target data is not available in wayback or the available data is more than 20 MB. I've set a limit of 20 MB in fetched data. If it exceeds the limit then data will be not stored in database as this amount of data will be not processed by browser at users end.

**Comment by bootyhunt3r** [comment]
Is there anywhere we can connect , I have some a question regarding the script , please give it to me if there's any platform.

**Comment by r3curs1v3-pr0xy** [comment]
You can connect with me through twitter [r3curs1v3_pr0xy](https://twitter.com/r3curs1v3_pr0xy) or discord: r3curs1v3_pr0xy#3989
