### ISSUE TITLE
nmp error 

### ISSUE THREAD

**Issue by elixirop** [r3curs1v3-pr0xy/vajra#12]
Im trying to install in kali lunux 

![image](https://user-images.githubusercontent.com/68217482/111815857-890fc380-88b2-11eb-90ec-57b3e4ff2f98.png)

**Comment by r3curs1v3-pr0xy** [comment]
These are only warnings not error. You can ignore this as it is for informational purpose. However, to install it in kali, you need to manually install CouchDB as installation script is for Ubuntu only.
