### ISSUE TITLE
Couchdb Error

### ISSUE THREAD

**Issue by anggipradana** [r3curs1v3-pr0xy/vajra#22]
I got error in Couchdb installation, here the screenshot
![image](https://user-images.githubusercontent.com/26999397/114993166-bf4a5e00-9ec5-11eb-8bcf-73100feff2ea.png)

**Comment by r3curs1v3-pr0xy** [comment]
This is couchDB container logs. It is for informational purpose only.

**Comment by anggipradana** [comment]
I have waited about 10 minutes, but the error because there is no _user database still appears

**Comment by r3curs1v3-pr0xy** [comment]
Since it is only logs so you need not to be worry about this. Add any target to the scan and it will create a database with target name in CouchDB. This will remove no database warning in logs.

**Comment by anggipradana** [comment]
Oke, thank you for the explanation and the quick response 🙏
