### ISSUE TITLE
tutorial is banned by youtube

### ISSUE THREAD

**Issue by wangsanshi123** [r3curs1v3-pr0xy/vajra#25]
Follow this tutorial: https://www.youtube.com/watch?v=YKAKIaHYKP0

_Originally posted by @r3curs1v3-pr0xy in https://github.com/r3curs1v3-pr0xy/vajra/issues/6#issuecomment-798850830_

can you guy provide a new one?thanks

**Comment by r3curs1v3-pr0xy** [comment]
You can follow this simple instructions: https://github.com/r3curs1v3-pr0xy/vajra/wiki/Running-with-docker-compose
