### ISSUE TITLE
getting errors and how to run this after insstallation

### ISSUE THREAD

**Issue by m41kdev3lops** [r3curs1v3-pr0xy/vajra#3]
run `npm fund` for details

found 2 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
npm WARN saveError ENOENT: no such file or directory, open '/home/kali/vajra/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/kali/vajra/package.json'
npm WARN vajra No description
npm WARN vajra No repository field.
npm WARN vajra No README data
npm WARN vajra No license field.

+ cookie-parser@1.4.5
updated 1 package and audited 319 packages in 2.811s

2 packages are looking for funding
  run `npm fund` for details

found 2 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
npm WARN saveError ENOENT: no such file or directory, open '/home/kali/vajra/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/kali/vajra/package.json'
npm WARN vajra No description
npm WARN vajra No repository field.
npm WARN vajra No README data
npm WARN vajra No license field.

+ cradle@0.7.1
updated 1 package and audited 319 packages in 2.823s

2 packages are looking for funding
  run `npm fund` for details

found 2 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
npm WARN saveError ENOENT: no such file or directory, open '/home/kali/vajra/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/kali/vajra/package.json'
npm WARN vajra No description
npm WARN vajra No repository field.
npm WARN vajra No README data
npm WARN vajra No license field.

+ ejs@3.1.6
updated 1 package and audited 319 packages in 2.882s

2 packages are looking for funding
  run `npm fund` for details

found 2 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
npm WARN saveError ENOENT: no such file or directory, open '/home/kali/vajra/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/kali/vajra/package.json'
npm WARN vajra No description
npm WARN vajra No repository field.
npm WARN vajra No README data
npm WARN vajra No license field.

+ express@4.17.1
updated 1 package and audited 319 packages in 2.871s

2 packages are looking for funding
  run `npm fund` for details

found 2 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
npm WARN saveError ENOENT: no such file or directory, open '/home/kali/vajra/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/kali/vajra/package.json'
npm WARN vajra No description
npm WARN vajra No repository field.
npm WARN vajra No README data
npm WARN vajra No license field.

+ express-rate-limit@5.2.6
updated 1 package and audited 319 packages in 2.478s

2 packages are looking for funding
  run `npm fund` for details

found 2 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
npm WARN saveError ENOENT: no such file or directory, open '/home/kali/vajra/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/kali/vajra/package.json'
npm WARN vajra No description
npm WARN vajra No repository field.
npm WARN vajra No README data
npm WARN vajra No license field.

+ fs@0.0.1-security
updated 1 package and audited 319 packages in 2.86s

2 packages are looking for funding
  run `npm fund` for details

found 2 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
npm WARN saveError ENOENT: no such file or directory, open '/home/kali/vajra/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/kali/vajra/package.json'
npm WARN vajra No description
npm WARN vajra No repository field.
npm WARN vajra No README data
npm WARN vajra No license field.

+ http@0.0.1-security
updated 1 package and audited 319 packages in 2.654s

2 packages are looking for funding
  run `npm fund` for details

found 2 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
npm WARN saveError ENOENT: no such file or directory, open '/home/kali/vajra/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/kali/vajra/package.json'
npm WARN vajra No description
npm WARN vajra No repository field.
npm WARN vajra No README data
npm WARN vajra No license field.

+ jsdom@16.5.1
updated 1 package and audited 319 packages in 3.737s

2 packages are looking for funding
  run `npm fund` for details

found 2 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
npm WARN saveError ENOENT: no such file or directory, open '/home/kali/vajra/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/kali/vajra/package.json'
npm WARN vajra No description
npm WARN vajra No repository field.
npm WARN vajra No README data
npm WARN vajra No license field.

+ jsonwebtoken@8.5.1
updated 1 package and audited 319 packages in 2.661s

2 packages are looking for funding
  run `npm fund` for details

found 2 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
npm WARN saveError ENOENT: no such file or directory, open '/home/kali/vajra/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/kali/vajra/package.json'
npm WARN vajra No description
npm WARN vajra No repository field.
npm WARN vajra No README data
npm WARN vajra No license field.

+ path@0.12.7
updated 1 package and audited 319 packages in 3.108s

2 packages are looking for funding
  run `npm fund` for details

found 2 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
npm WARN saveError ENOENT: no such file or directory, open '/home/kali/vajra/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/kali/vajra/package.json'
npm WARN vajra No description
npm WARN vajra No repository field.
npm WARN vajra No README data
npm WARN vajra No license field.

+ readline@1.3.0
updated 1 package and audited 319 packages in 3.162s

2 packages are looking for funding
  run `npm fund` for details

found 2 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
npm WARN saveError ENOENT: no such file or directory, open '/home/kali/vajra/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/kali/vajra/package.json'
npm WARN vajra No description
npm WARN vajra No repository field.
npm WARN vajra No README data
npm WARN vajra No license field.

+ xterm@4.11.0
updated 1 package and audited 319 packages in 3.999s

2 packages are looking for funding
  run `npm fund` for details

found 2 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
npm WARN saveError ENOENT: no such file or directory, open '/home/kali/vajra/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/kali/vajra/package.json'
npm WARN vajra No description
npm WARN vajra No repository field.
npm WARN vajra No README data
npm WARN vajra No license field.

+ jquery@3.6.0
updated 1 package and audited 319 packages in 3.224s

2 packages are looking for funding
  run `npm fund` for details

found 2 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by Ali3nWar3** [comment]
have the same error

**Comment by r3curs1v3-pr0xy** [comment]
This warning is due to package.json file that I haven't included in the repo. You can ignore this warning as it will not affect the working of the framework.  

To run the framework, go to vajra directory and type ```node index.js```.
