### ISSUE TITLE
result are not showing

### ISSUE THREAD

**Issue by mrrootx145** [r3curs1v3-pr0xy/vajra#4]
[
![Screenshot from 2021-03-13 06-04-32](https://user-images.githubusercontent.com/69041491/111032814-15923000-8434-11eb-8338-344256ab82b1.png)
](url)

**Comment by r3curs1v3-pr0xy** [comment]
Have you provided a valid domain name?

**Comment by bootyhunt3r** [comment]
I am also having this issue , any idea how to solve this ? I used everything , restarted the service too ,  but no luck !

**Comment by r3curs1v3-pr0xy** [comment]
Is CouchDB is running on localhost? 

You can verify this by ```curl http://127.0.0.1:5984```

**Comment by mrrootx145** [comment]
Solve this issue using change password of couchDB  is `hackwithme` and restart service

**Comment by mrrootx145** [comment]
Follow this steps : https://youtu.be/YKAKIaHYKP0
