### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by bootyhunt3r** [r3curs1v3-pr0xy/vajra#5]
Hello man , 
I really really appreciate this project , I just want to know how to use this in my VPS , I recently purchases a VPS service and can you tell me how to start the recon with this using my VPS ?

**Comment by r3curs1v3-pr0xy** [comment]
I'm making a youtube video on installation part.  You can follow the video tutorial to install and use it.

**Comment by bootyhunt3r** [comment]
Any idea till when the video will be uploaded ?
