### ISSUE TITLE
Unable to install on google VPS! 

### ISSUE THREAD

**Issue by karmickei** [r3curs1v3-pr0xy/vajra#7]
i don't know what the fix is for this error! tho i'll keep looking for solution, but kindly if you are aware then please share the fix! or any remedy!... 
ERROR: 
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
root@offsec:~/vajra/install# sudo npm audit fix
npm WARN vajra@1.0.0 No repository field.

up to date in 0.926s

2 packages are looking for funding
  run `npm fund` for details

fixed 0 of 1 vulnerability in 191 scanned packages
  1 vulnerability required manual review and could not be updated

**Comment by r3curs1v3-pr0xy** [comment]
It is for informational purpose only. You can ignore this warning as it has no effect on the framework. If you face any other issue then follow this tutorial on youtube. 

https://www.youtube.com/watch?v=YKAKIaHYKP0
