### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by bootyhunt3r** [r3curs1v3-pr0xy/vajra#8]
Hello @r3curs1v3-pr0xy , this framework is truly awesome , but can you tell me how to use it to finding everything for all the subdomains ? Like I want to do directory bruteforcing , but how can I add all the subdomains for that ?

**Comment by r3curs1v3-pr0xy** [comment]
Thanks for your feedback @bootyhunt3r 

If you want to include subdomains in any of the scan then make sure you find subdomains first. I mean to say subdomains must be available in database as the scans are dependent on it.

After getting all subdomains, select your type of scans and include subdomains in it. 

**Note:** Currently, Fuzzing with Custom Generated Wordlist is not supported on subdomains. You can use it on root domain only. Rest two of the options are available for both root domain and subdomains.

For more on Usage Guide, read this blog post: https://hackwithproxy.medium.com/introducing-vajra-an-advanced-web-hacking-framework-bd8307a01aa8

**Comment by bootyhunt3r** [comment]
Yeah , but how to include subdomains , just click on the subdomains section ?
