### ISSUE TITLE
config.yaml file for Certeagle not provided

### ISSUE THREAD

**Issue by pendragonn** [r3curs1v3-pr0xy/vajra#9]
certeagle.py looks for this file on line 121 which is not provided, then it crashes.

**Comment by r3curs1v3-pr0xy** [comment]
Yesterday, I got to know about this. It uploaded it in CertEagle repo but forgot to change commit id in submodule of Github. You can create a config.yaml file inside CertEagle directory with any random content as we have nothing to do with config.yaml file

**Comment by r3curs1v3-pr0xy** [comment]
https://github.com/r3curs1v3-pr0xy/vajra/commit/134babb3c6746d04daa984b4f08742ea55f01617 Fixed this issue
